# Generated by Django 3.1.5 on 2021-01-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaDenuncinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120, verbose_name='Nombre del desaparecido')),
                ('Appellido', models.TextField(max_length=200, verbose_name='Apellido del desaparecido')),
                ('Telefono', models.IntegerField(max_length=10)),
                ('TonoDePiel', models.CharField(max_length=120, verbose_name='Color de piel del desaparecido')),
                ('Edad', models.IntegerField(max_length=3)),
                ('ColorOjos', models.CharField(max_length=100, verbose_name='Color de los ojos')),
                ('Estatura', models.FloatField(max_length=4, verbose_name='Estatura del desapareido')),
                ('Relacion', models.TextField(max_length=200, verbose_name='La relacion entre el denunciante y el desaparecido')),
            ],
        ),
    ]
