# Generated by Django 3.1.5 on 2021-01-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadenuncinate',
            name='Telefono',
            field=models.IntegerField(),
        ),
    ]
