# Generated by Django 3.1.5 on 2021-01-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_auto_20210124_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadenuncinate',
            name='Edad',
            field=models.IntegerField(),
        ),
    ]
