# Generated by Django 3.1.5 on 2021-02-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_reportaraparecimiento_sospecho_ultimoavistamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personadesaparecida',
            name='Fotografia',
        ),
    ]
