# Generated by Django 3.1.5 on 2021-02-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_remove_personadesaparecida_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadenuncinate',
            name='Appellido',
            field=models.TextField(max_length=200, verbose_name='Apellido del denunciante'),
        ),
        migrations.AlterField(
            model_name='personadenuncinate',
            name='Estatura',
            field=models.FloatField(max_length=4, verbose_name='Estatura del denunciante'),
        ),
        migrations.AlterField(
            model_name='personadenuncinate',
            name='Nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre del denunciante'),
        ),
        migrations.AlterField(
            model_name='personadenuncinate',
            name='TonoDePiel',
            field=models.CharField(max_length=120, verbose_name='Color de piel del denunciante'),
        ),
    ]
